#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlohaFlyAdmin.ToGoExport
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="togo")]
	public partial class DBToGoDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Определения метода расширяемости
    partial void OnCreated();
    #endregion
		
		public DBToGoDataContext() : 
				base(global::AlohaFlyAdmin.Properties.Settings.Default.togoConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DBToGoDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBToGoDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBToGoDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBToGoDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Address> Address
		{
			get
			{
				return this.GetTable<Address>();
			}
		}
		
		public System.Data.Linq.Table<Client> Client
		{
			get
			{
				return this.GetTable<Client>();
			}
		}
		
		public System.Data.Linq.Table<ClientType> ClientType
		{
			get
			{
				return this.GetTable<ClientType>();
			}
		}
		
		public System.Data.Linq.Table<Couriers> Couriers
		{
			get
			{
				return this.GetTable<Couriers>();
			}
		}
		
		public System.Data.Linq.Table<DayTime> DayTime
		{
			get
			{
				return this.GetTable<DayTime>();
			}
		}
		
		public System.Data.Linq.Table<DeliveryZone> DeliveryZone
		{
			get
			{
				return this.GetTable<DeliveryZone>();
			}
		}
		
		public System.Data.Linq.Table<MeasureUnitNames> MeasureUnitNames
		{
			get
			{
				return this.GetTable<MeasureUnitNames>();
			}
		}
		
		public System.Data.Linq.Table<Menu> Menu
		{
			get
			{
				return this.GetTable<Menu>();
			}
		}
		
		public System.Data.Linq.Table<Operators> Operators
		{
			get
			{
				return this.GetTable<Operators>();
			}
		}
		
		public System.Data.Linq.Table<OrderContent> OrderContent
		{
			get
			{
				return this.GetTable<OrderContent>();
			}
		}
		
		public System.Data.Linq.Table<Orders> Orders
		{
			get
			{
				return this.GetTable<Orders>();
			}
		}
		
		public System.Data.Linq.Table<RKeeperMenu> RKeeperMenu
		{
			get
			{
				return this.GetTable<RKeeperMenu>();
			}
		}
		
		public System.Data.Linq.Table<SaleChannel> SaleChannel
		{
			get
			{
				return this.GetTable<SaleChannel>();
			}
		}
		
		public System.Data.Linq.Table<Status> Status
		{
			get
			{
				return this.GetTable<Status>();
			}
		}
		
		public System.Data.Linq.Table<StickCatalog> StickCatalog
		{
			get
			{
				return this.GetTable<StickCatalog>();
			}
		}
		
		public System.Data.Linq.Table<StickContent> StickContent
		{
			get
			{
				return this.GetTable<StickContent>();
			}
		}
		
		public System.Data.Linq.Table<sysdiagrams> sysdiagrams
		{
			get
			{
				return this.GetTable<sysdiagrams>();
			}
		}
		
		public System.Data.Linq.Table<Tel> Tel
		{
			get
			{
				return this.GetTable<Tel>();
			}
		}
		
		public System.Data.Linq.Table<Version> Version
		{
			get
			{
				return this.GetTable<Version>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Address")]
	public partial class Address
	{
		
		private int _ID;
		
		private int _ClientID;
		
		private string _Address1;
		
		private string _Subway;
		
		private System.Nullable<int> _Zone;
		
		private string _MapURL;
		
		private bool _BL;
		
		private string _Comment;
		
		private System.Nullable<bool> _Active;
		
		public Address()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClientID", DbType="Int NOT NULL")]
		public int ClientID
		{
			get
			{
				return this._ClientID;
			}
			set
			{
				if ((this._ClientID != value))
				{
					this._ClientID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Address", Storage="_Address1", DbType="NVarChar(255)")]
		public string Address1
		{
			get
			{
				return this._Address1;
			}
			set
			{
				if ((this._Address1 != value))
				{
					this._Address1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Subway", DbType="NVarChar(50)")]
		public string Subway
		{
			get
			{
				return this._Subway;
			}
			set
			{
				if ((this._Subway != value))
				{
					this._Subway = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zone", DbType="Int")]
		public System.Nullable<int> Zone
		{
			get
			{
				return this._Zone;
			}
			set
			{
				if ((this._Zone != value))
				{
					this._Zone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MapURL", DbType="NVarChar(MAX)")]
		public string MapURL
		{
			get
			{
				return this._MapURL;
			}
			set
			{
				if ((this._MapURL != value))
				{
					this._MapURL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BL", DbType="Bit NOT NULL")]
		public bool BL
		{
			get
			{
				return this._BL;
			}
			set
			{
				if ((this._BL != value))
				{
					this._BL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comment", DbType="NVarChar(255)")]
		public string Comment
		{
			get
			{
				return this._Comment;
			}
			set
			{
				if ((this._Comment != value))
				{
					this._Comment = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Active", DbType="Bit")]
		public System.Nullable<bool> Active
		{
			get
			{
				return this._Active;
			}
			set
			{
				if ((this._Active != value))
				{
					this._Active = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Client")]
	public partial class Client
	{
		
		private int _ID;
		
		private string _Name;
		
		private string _SecondName;
		
		private string _FamilyName;
		
		private string _Aliace;
		
		private bool _BL;
		
		private string _Comment;
		
		private string _Records;
		
		private string _Email;
		
		private bool _CashBack;
		
		public Client()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SecondName", DbType="NVarChar(50)")]
		public string SecondName
		{
			get
			{
				return this._SecondName;
			}
			set
			{
				if ((this._SecondName != value))
				{
					this._SecondName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FamilyName", DbType="NVarChar(50)")]
		public string FamilyName
		{
			get
			{
				return this._FamilyName;
			}
			set
			{
				if ((this._FamilyName != value))
				{
					this._FamilyName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Aliace", DbType="NChar(10)")]
		public string Aliace
		{
			get
			{
				return this._Aliace;
			}
			set
			{
				if ((this._Aliace != value))
				{
					this._Aliace = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BL", DbType="Bit NOT NULL")]
		public bool BL
		{
			get
			{
				return this._BL;
			}
			set
			{
				if ((this._BL != value))
				{
					this._BL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comment", DbType="NVarChar(255)")]
		public string Comment
		{
			get
			{
				return this._Comment;
			}
			set
			{
				if ((this._Comment != value))
				{
					this._Comment = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Records", DbType="NVarChar(MAX)")]
		public string Records
		{
			get
			{
				return this._Records;
			}
			set
			{
				if ((this._Records != value))
				{
					this._Records = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NChar(50) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CashBack", DbType="Bit NOT NULL")]
		public bool CashBack
		{
			get
			{
				return this._CashBack;
			}
			set
			{
				if ((this._CashBack != value))
				{
					this._CashBack = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ClientType")]
	public partial class ClientType
	{
		
		private byte _ID;
		
		private string _Name;
		
		public ClientType()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="TinyInt NOT NULL")]
		public byte ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Couriers")]
	public partial class Couriers
	{
		
		private int _ID;
		
		private string _Name;
		
		public Couriers()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DayTime")]
	public partial class DayTime
	{
		
		private System.TimeSpan _Start;
		
		private System.TimeSpan _Finish;
		
		public DayTime()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Start", DbType="Time NOT NULL")]
		public System.TimeSpan Start
		{
			get
			{
				return this._Start;
			}
			set
			{
				if ((this._Start != value))
				{
					this._Start = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Finish", DbType="Time NOT NULL")]
		public System.TimeSpan Finish
		{
			get
			{
				return this._Finish;
			}
			set
			{
				if ((this._Finish != value))
				{
					this._Finish = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DeliveryZone")]
	public partial class DeliveryZone
	{
		
		private int _ID;
		
		private string _Name;
		
		private decimal _DayPrice;
		
		private decimal _NightPrice;
		
		private decimal _MinOrderSumm;
		
		public DeliveryZone()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DayPrice", DbType="Decimal(18,2) NOT NULL")]
		public decimal DayPrice
		{
			get
			{
				return this._DayPrice;
			}
			set
			{
				if ((this._DayPrice != value))
				{
					this._DayPrice = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NightPrice", DbType="Decimal(18,2) NOT NULL")]
		public decimal NightPrice
		{
			get
			{
				return this._NightPrice;
			}
			set
			{
				if ((this._NightPrice != value))
				{
					this._NightPrice = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MinOrderSumm", DbType="Decimal(18,2) NOT NULL")]
		public decimal MinOrderSumm
		{
			get
			{
				return this._MinOrderSumm;
			}
			set
			{
				if ((this._MinOrderSumm != value))
				{
					this._MinOrderSumm = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MeasureUnitNames")]
	public partial class MeasureUnitNames
	{
		
		private System.Nullable<int> _id;
		
		private string _name;
		
		public MeasureUnitNames()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int")]
		public System.Nullable<int> id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(10)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Menu")]
	public partial class Menu
	{
		
		private int _ID;
		
		private string _Code;
		
		private string _Name;
		
		private string _Weight;
		
		private decimal _Cost;
		
		private string _Category;
		
		private string _sifr;
		
		private bool _Active;
		
		public Menu()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this._Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Weight", DbType="NVarChar(50)")]
		public string Weight
		{
			get
			{
				return this._Weight;
			}
			set
			{
				if ((this._Weight != value))
				{
					this._Weight = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cost", DbType="Decimal(18,2) NOT NULL")]
		public decimal Cost
		{
			get
			{
				return this._Cost;
			}
			set
			{
				if ((this._Cost != value))
				{
					this._Cost = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Category", DbType="NVarChar(50)")]
		public string Category
		{
			get
			{
				return this._Category;
			}
			set
			{
				if ((this._Category != value))
				{
					this._Category = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sifr", DbType="NChar(10)")]
		public string sifr
		{
			get
			{
				return this._sifr;
			}
			set
			{
				if ((this._sifr != value))
				{
					this._sifr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Active", DbType="Bit NOT NULL")]
		public bool Active
		{
			get
			{
				return this._Active;
			}
			set
			{
				if ((this._Active != value))
				{
					this._Active = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Operators")]
	public partial class Operators
	{
		
		private int _ID;
		
		private string _Name;
		
		public Operators()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.OrderContent")]
	public partial class OrderContent
	{
		
		private int _ID;
		
		private int _OrderID;
		
		private System.Nullable<int> _Code;
		
		private string _Name;
		
		private System.Nullable<decimal> _Amount;
		
		private string _MeashureItems;
		
		private System.Nullable<decimal> _Price;
		
		private string _Comment;
		
		private string _WarmUP;
		
		public OrderContent()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderID", DbType="Int NOT NULL")]
		public int OrderID
		{
			get
			{
				return this._OrderID;
			}
			set
			{
				if ((this._OrderID != value))
				{
					this._OrderID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="Int")]
		public System.Nullable<int> Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this._Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(255)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Amount", DbType="Decimal(18,1)")]
		public System.Nullable<decimal> Amount
		{
			get
			{
				return this._Amount;
			}
			set
			{
				if ((this._Amount != value))
				{
					this._Amount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MeashureItems", DbType="NChar(10)")]
		public string MeashureItems
		{
			get
			{
				return this._MeashureItems;
			}
			set
			{
				if ((this._MeashureItems != value))
				{
					this._MeashureItems = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this._Price = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comment", DbType="NVarChar(250)")]
		public string Comment
		{
			get
			{
				return this._Comment;
			}
			set
			{
				if ((this._Comment != value))
				{
					this._Comment = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WarmUP", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string WarmUP
		{
			get
			{
				return this._WarmUP;
			}
			set
			{
				if ((this._WarmUP != value))
				{
					this._WarmUP = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Orders")]
	public partial class Orders
	{
		
		private int _ID;
		
		private int _ClientID;
		
		private int _AddressID;
		
		private int _TelID;
		
		private string _Courier;
		
		private string _Operator;
		
		private System.DateTime _CreateDate;
		
		private System.Nullable<System.DateTime> _DateDelivery;
		
		private System.Nullable<System.TimeSpan> _TimeDelivery;
		
		private System.Nullable<System.DateTime> _DateReady;
		
		private System.Nullable<System.TimeSpan> _TimeReady;
		
		private System.Nullable<int> _Status;
		
		private System.Nullable<int> _SaleChannelID;
		
		private System.Nullable<decimal> _Summ;
		
		private System.Nullable<decimal> _DeliveryPrice;
		
		private string _CommentCourier;
		
		private string _CommentKitchen;
		
		private System.TimeSpan _CreateTime;
		
		private string _FoodTime;
		
		public Orders()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClientID", DbType="Int NOT NULL")]
		public int ClientID
		{
			get
			{
				return this._ClientID;
			}
			set
			{
				if ((this._ClientID != value))
				{
					this._ClientID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AddressID", DbType="Int NOT NULL")]
		public int AddressID
		{
			get
			{
				return this._AddressID;
			}
			set
			{
				if ((this._AddressID != value))
				{
					this._AddressID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TelID", DbType="Int NOT NULL")]
		public int TelID
		{
			get
			{
				return this._TelID;
			}
			set
			{
				if ((this._TelID != value))
				{
					this._TelID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Courier", DbType="NVarChar(50)")]
		public string Courier
		{
			get
			{
				return this._Courier;
			}
			set
			{
				if ((this._Courier != value))
				{
					this._Courier = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Operator", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Operator
		{
			get
			{
				return this._Operator;
			}
			set
			{
				if ((this._Operator != value))
				{
					this._Operator = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="Date NOT NULL")]
		public System.DateTime CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this._CreateDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateDelivery", DbType="Date")]
		public System.Nullable<System.DateTime> DateDelivery
		{
			get
			{
				return this._DateDelivery;
			}
			set
			{
				if ((this._DateDelivery != value))
				{
					this._DateDelivery = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeDelivery", DbType="Time")]
		public System.Nullable<System.TimeSpan> TimeDelivery
		{
			get
			{
				return this._TimeDelivery;
			}
			set
			{
				if ((this._TimeDelivery != value))
				{
					this._TimeDelivery = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateReady", DbType="Date")]
		public System.Nullable<System.DateTime> DateReady
		{
			get
			{
				return this._DateReady;
			}
			set
			{
				if ((this._DateReady != value))
				{
					this._DateReady = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeReady", DbType="Time")]
		public System.Nullable<System.TimeSpan> TimeReady
		{
			get
			{
				return this._TimeReady;
			}
			set
			{
				if ((this._TimeReady != value))
				{
					this._TimeReady = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Int")]
		public System.Nullable<int> Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this._Status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SaleChannelID", DbType="Int")]
		public System.Nullable<int> SaleChannelID
		{
			get
			{
				return this._SaleChannelID;
			}
			set
			{
				if ((this._SaleChannelID != value))
				{
					this._SaleChannelID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Summ", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Summ
		{
			get
			{
				return this._Summ;
			}
			set
			{
				if ((this._Summ != value))
				{
					this._Summ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeliveryPrice", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> DeliveryPrice
		{
			get
			{
				return this._DeliveryPrice;
			}
			set
			{
				if ((this._DeliveryPrice != value))
				{
					this._DeliveryPrice = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CommentCourier", DbType="NVarChar(250)")]
		public string CommentCourier
		{
			get
			{
				return this._CommentCourier;
			}
			set
			{
				if ((this._CommentCourier != value))
				{
					this._CommentCourier = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CommentKitchen", DbType="NVarChar(250)")]
		public string CommentKitchen
		{
			get
			{
				return this._CommentKitchen;
			}
			set
			{
				if ((this._CommentKitchen != value))
				{
					this._CommentKitchen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateTime", DbType="Time NOT NULL")]
		public System.TimeSpan CreateTime
		{
			get
			{
				return this._CreateTime;
			}
			set
			{
				if ((this._CreateTime != value))
				{
					this._CreateTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FoodTime", DbType="NVarChar(10)")]
		public string FoodTime
		{
			get
			{
				return this._FoodTime;
			}
			set
			{
				if ((this._FoodTime != value))
				{
					this._FoodTime = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.RKeeperMenu")]
	public partial class RKeeperMenu
	{
		
		private System.Nullable<int> _Sifr;
		
		private string _Name;
		
		private System.Nullable<decimal> _Price;
		
		private System.Nullable<int> _Code;
		
		private System.Nullable<char> _TreeType;
		
		private System.Nullable<byte> _LimitPrice;
		
		private System.Nullable<int> _Categ;
		
		private System.Nullable<int> _Parent;
		
		private System.Nullable<int> _Link;
		
		private System.Nullable<int> _Stream;
		
		private System.Nullable<bool> _Lack;
		
		private string _DesignSifr;
		
		private string _AltName;
		
		private System.Nullable<byte> _Nalog;
		
		private string _Barcode;
		
		private string _Image;
		
		private string _Consumma;
		
		private string _MinRest;
		
		private string _PrnRest;
		
		private string _CookTime;
		
		private string _Dispenser;
		
		private string _DispKoef;
		
		private string _Access;
		
		private string _Flags;
		
		private string _Tara;
		
		private string _CntPrice;
		
		private string _BackBGR;
		
		private string _FontBGR;
		
		private string _TaxGroup;
		
		private string _MinPrice;
		
		private string _Reccom;
		
		private string _DateIncl;
		
		private string _DateExcl;
		
		private string _TimeIncl;
		
		private string _TimeExcl;
		
		private string _FWeek;
		
		private string _WeighK;
		
		public RKeeperMenu()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sifr", DbType="Int")]
		public System.Nullable<int> Sifr
		{
			get
			{
				return this._Sifr;
			}
			set
			{
				if ((this._Sifr != value))
				{
					this._Sifr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this._Price = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="Int")]
		public System.Nullable<int> Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this._Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TreeType", DbType="Char(1)")]
		public System.Nullable<char> TreeType
		{
			get
			{
				return this._TreeType;
			}
			set
			{
				if ((this._TreeType != value))
				{
					this._TreeType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LimitPrice", DbType="TinyInt")]
		public System.Nullable<byte> LimitPrice
		{
			get
			{
				return this._LimitPrice;
			}
			set
			{
				if ((this._LimitPrice != value))
				{
					this._LimitPrice = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Categ", DbType="Int")]
		public System.Nullable<int> Categ
		{
			get
			{
				return this._Categ;
			}
			set
			{
				if ((this._Categ != value))
				{
					this._Categ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Parent", DbType="Int")]
		public System.Nullable<int> Parent
		{
			get
			{
				return this._Parent;
			}
			set
			{
				if ((this._Parent != value))
				{
					this._Parent = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Link", DbType="Int")]
		public System.Nullable<int> Link
		{
			get
			{
				return this._Link;
			}
			set
			{
				if ((this._Link != value))
				{
					this._Link = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stream", DbType="Int")]
		public System.Nullable<int> Stream
		{
			get
			{
				return this._Stream;
			}
			set
			{
				if ((this._Stream != value))
				{
					this._Stream = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lack", DbType="Bit")]
		public System.Nullable<bool> Lack
		{
			get
			{
				return this._Lack;
			}
			set
			{
				if ((this._Lack != value))
				{
					this._Lack = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DesignSifr", DbType="NVarChar(50)")]
		public string DesignSifr
		{
			get
			{
				return this._DesignSifr;
			}
			set
			{
				if ((this._DesignSifr != value))
				{
					this._DesignSifr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AltName", DbType="NVarChar(50)")]
		public string AltName
		{
			get
			{
				return this._AltName;
			}
			set
			{
				if ((this._AltName != value))
				{
					this._AltName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nalog", DbType="TinyInt")]
		public System.Nullable<byte> Nalog
		{
			get
			{
				return this._Nalog;
			}
			set
			{
				if ((this._Nalog != value))
				{
					this._Nalog = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Barcode", DbType="NVarChar(50)")]
		public string Barcode
		{
			get
			{
				return this._Barcode;
			}
			set
			{
				if ((this._Barcode != value))
				{
					this._Barcode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Image", DbType="NVarChar(50)")]
		public string Image
		{
			get
			{
				return this._Image;
			}
			set
			{
				if ((this._Image != value))
				{
					this._Image = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Consumma", DbType="NVarChar(50)")]
		public string Consumma
		{
			get
			{
				return this._Consumma;
			}
			set
			{
				if ((this._Consumma != value))
				{
					this._Consumma = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MinRest", DbType="NVarChar(50)")]
		public string MinRest
		{
			get
			{
				return this._MinRest;
			}
			set
			{
				if ((this._MinRest != value))
				{
					this._MinRest = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrnRest", DbType="NVarChar(50)")]
		public string PrnRest
		{
			get
			{
				return this._PrnRest;
			}
			set
			{
				if ((this._PrnRest != value))
				{
					this._PrnRest = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CookTime", DbType="NVarChar(50)")]
		public string CookTime
		{
			get
			{
				return this._CookTime;
			}
			set
			{
				if ((this._CookTime != value))
				{
					this._CookTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dispenser", DbType="NVarChar(50)")]
		public string Dispenser
		{
			get
			{
				return this._Dispenser;
			}
			set
			{
				if ((this._Dispenser != value))
				{
					this._Dispenser = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DispKoef", DbType="NVarChar(50)")]
		public string DispKoef
		{
			get
			{
				return this._DispKoef;
			}
			set
			{
				if ((this._DispKoef != value))
				{
					this._DispKoef = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Access", DbType="NVarChar(50)")]
		public string Access
		{
			get
			{
				return this._Access;
			}
			set
			{
				if ((this._Access != value))
				{
					this._Access = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Flags", DbType="NVarChar(50)")]
		public string Flags
		{
			get
			{
				return this._Flags;
			}
			set
			{
				if ((this._Flags != value))
				{
					this._Flags = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tara", DbType="NVarChar(50)")]
		public string Tara
		{
			get
			{
				return this._Tara;
			}
			set
			{
				if ((this._Tara != value))
				{
					this._Tara = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CntPrice", DbType="NVarChar(50)")]
		public string CntPrice
		{
			get
			{
				return this._CntPrice;
			}
			set
			{
				if ((this._CntPrice != value))
				{
					this._CntPrice = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BackBGR", DbType="NVarChar(50)")]
		public string BackBGR
		{
			get
			{
				return this._BackBGR;
			}
			set
			{
				if ((this._BackBGR != value))
				{
					this._BackBGR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FontBGR", DbType="NVarChar(50)")]
		public string FontBGR
		{
			get
			{
				return this._FontBGR;
			}
			set
			{
				if ((this._FontBGR != value))
				{
					this._FontBGR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaxGroup", DbType="NVarChar(50)")]
		public string TaxGroup
		{
			get
			{
				return this._TaxGroup;
			}
			set
			{
				if ((this._TaxGroup != value))
				{
					this._TaxGroup = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MinPrice", DbType="NVarChar(50)")]
		public string MinPrice
		{
			get
			{
				return this._MinPrice;
			}
			set
			{
				if ((this._MinPrice != value))
				{
					this._MinPrice = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reccom", DbType="NVarChar(50)")]
		public string Reccom
		{
			get
			{
				return this._Reccom;
			}
			set
			{
				if ((this._Reccom != value))
				{
					this._Reccom = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateIncl", DbType="NVarChar(50)")]
		public string DateIncl
		{
			get
			{
				return this._DateIncl;
			}
			set
			{
				if ((this._DateIncl != value))
				{
					this._DateIncl = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateExcl", DbType="NVarChar(50)")]
		public string DateExcl
		{
			get
			{
				return this._DateExcl;
			}
			set
			{
				if ((this._DateExcl != value))
				{
					this._DateExcl = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeIncl", DbType="NVarChar(50)")]
		public string TimeIncl
		{
			get
			{
				return this._TimeIncl;
			}
			set
			{
				if ((this._TimeIncl != value))
				{
					this._TimeIncl = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeExcl", DbType="NVarChar(50)")]
		public string TimeExcl
		{
			get
			{
				return this._TimeExcl;
			}
			set
			{
				if ((this._TimeExcl != value))
				{
					this._TimeExcl = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FWeek", DbType="NVarChar(50)")]
		public string FWeek
		{
			get
			{
				return this._FWeek;
			}
			set
			{
				if ((this._FWeek != value))
				{
					this._FWeek = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WeighK", DbType="NVarChar(50)")]
		public string WeighK
		{
			get
			{
				return this._WeighK;
			}
			set
			{
				if ((this._WeighK != value))
				{
					this._WeighK = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SaleChannel")]
	public partial class SaleChannel
	{
		
		private int _ID;
		
		private string _Name;
		
		private System.Nullable<bool> _Active;
		
		public SaleChannel()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NChar(20)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Active", DbType="Bit")]
		public System.Nullable<bool> Active
		{
			get
			{
				return this._Active;
			}
			set
			{
				if ((this._Active != value))
				{
					this._Active = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Status")]
	public partial class Status
	{
		
		private int _ID;
		
		private string _Name;
		
		private bool _Active;
		
		public Status()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Active", DbType="Bit NOT NULL")]
		public bool Active
		{
			get
			{
				return this._Active;
			}
			set
			{
				if ((this._Active != value))
				{
					this._Active = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.StickCatalog")]
	public partial class StickCatalog
	{
		
		private int _ID;
		
		private string _Code;
		
		private string _NameRU;
		
		private string _NameENG;
		
		private System.Nullable<System.DateTime> _CreateDate;
		
		public StickCatalog()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="NVarChar(9) NOT NULL", CanBeNull=false)]
		public string Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this._Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NameRU", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string NameRU
		{
			get
			{
				return this._NameRU;
			}
			set
			{
				if ((this._NameRU != value))
				{
					this._NameRU = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NameENG", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string NameENG
		{
			get
			{
				return this._NameENG;
			}
			set
			{
				if ((this._NameENG != value))
				{
					this._NameENG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="Date")]
		public System.Nullable<System.DateTime> CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this._CreateDate = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.StickContent")]
	public partial class StickContent
	{
		
		private int _StickID;
		
		private int _PartID;
		
		private int _PartNumb;
		
		private string _PartNameRU;
		
		private string _PartNameENG;
		
		private string _WarmUp;
		
		public StickContent()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StickID", DbType="Int NOT NULL")]
		public int StickID
		{
			get
			{
				return this._StickID;
			}
			set
			{
				if ((this._StickID != value))
				{
					this._StickID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PartID", DbType="Int NOT NULL")]
		public int PartID
		{
			get
			{
				return this._PartID;
			}
			set
			{
				if ((this._PartID != value))
				{
					this._PartID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PartNumb", DbType="Int NOT NULL")]
		public int PartNumb
		{
			get
			{
				return this._PartNumb;
			}
			set
			{
				if ((this._PartNumb != value))
				{
					this._PartNumb = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PartNameRU", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string PartNameRU
		{
			get
			{
				return this._PartNameRU;
			}
			set
			{
				if ((this._PartNameRU != value))
				{
					this._PartNameRU = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PartNameENG", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string PartNameENG
		{
			get
			{
				return this._PartNameENG;
			}
			set
			{
				if ((this._PartNameENG != value))
				{
					this._PartNameENG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WarmUp", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string WarmUp
		{
			get
			{
				return this._WarmUp;
			}
			set
			{
				if ((this._WarmUp != value))
				{
					this._WarmUp = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.sysdiagrams")]
	public partial class sysdiagrams
	{
		
		private string _name;
		
		private int _principal_id;
		
		private int _diagram_id;
		
		private System.Nullable<int> _version;
		
		private System.Data.Linq.Binary _definition;
		
		public sysdiagrams()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(128) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_principal_id", DbType="Int NOT NULL")]
		public int principal_id
		{
			get
			{
				return this._principal_id;
			}
			set
			{
				if ((this._principal_id != value))
				{
					this._principal_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diagram_id", DbType="Int NOT NULL")]
		public int diagram_id
		{
			get
			{
				return this._diagram_id;
			}
			set
			{
				if ((this._diagram_id != value))
				{
					this._diagram_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_version", DbType="Int")]
		public System.Nullable<int> version
		{
			get
			{
				return this._version;
			}
			set
			{
				if ((this._version != value))
				{
					this._version = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_definition", DbType="VarBinary(MAX)", CanBeNull=true, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary definition
		{
			get
			{
				return this._definition;
			}
			set
			{
				if ((this._definition != value))
				{
					this._definition = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tel")]
	public partial class Tel
	{
		
		private int _ID;
		
		private int _ClientID;
		
		private string _Number;
		
		private bool _Active;
		
		private bool _BL;
		
		public Tel()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClientID", DbType="Int NOT NULL")]
		public int ClientID
		{
			get
			{
				return this._ClientID;
			}
			set
			{
				if ((this._ClientID != value))
				{
					this._ClientID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Number", DbType="Char(15) NOT NULL", CanBeNull=false)]
		public string Number
		{
			get
			{
				return this._Number;
			}
			set
			{
				if ((this._Number != value))
				{
					this._Number = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Active", DbType="Bit NOT NULL")]
		public bool Active
		{
			get
			{
				return this._Active;
			}
			set
			{
				if ((this._Active != value))
				{
					this._Active = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BL", DbType="Bit NOT NULL")]
		public bool BL
		{
			get
			{
				return this._BL;
			}
			set
			{
				if ((this._BL != value))
				{
					this._BL = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Version")]
	public partial class Version
	{
		
		private string _ver;
		
		public Version()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ver", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string ver
		{
			get
			{
				return this._ver;
			}
			set
			{
				if ((this._ver != value))
				{
					this._ver = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
