// <auto-generated />
namespace AlohaService.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AirCompanies1CCodes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AirCompanies1CCodes));
        
        string IMigrationMetadata.Id
        {
            get { return "201812061426467_AirCompanies1CCodes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
