//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlohaFly.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(" https://18.216.147.247/AlohaService/AlohaService.svc")]
        public string DBAddress {
            get {
                return ((string)(this["DBAddress"]));
            }
            set {
                this["DBAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://18.216.147.247/AlohaServiceStaging/AlohaService.svc")]
        public string DBAddressRelease {
            get {
                return ((string)(this["DBAddressRelease"]));
            }
            set {
                this["DBAddressRelease"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("195.13.163.36")]
        public string SHIP {
            get {
                return ((string)(this["SHIP"]));
            }
            set {
                this["SHIP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4049")]
        public int SHPort {
            get {
                return ((int)(this["SHPort"]));
            }
            set {
                this["SHPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Aloha")]
        public string SHLogin {
            get {
                return ((string)(this["SHLogin"]));
            }
            set {
                this["SHLogin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("aloha123")]
        public string SHPass {
            get {
                return ((string)(this["SHPass"]));
            }
            set {
                this["SHPass"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int SHRidPlace {
            get {
                return ((int)(this["SHRidPlace"]));
            }
            set {
                this["SHRidPlace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("667")]
        public int SHRidCatExp {
            get {
                return ((int)(this["SHRidCatExp"]));
            }
            set {
                this["SHRidCatExp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AlohaFly")]
        public string SHDocPrefix {
            get {
                return ((string)(this["SHDocPrefix"]));
            }
            set {
                this["SHDocPrefix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Test Document from AlohaFly")]
        public string SHDocComment {
            get {
                return ((string)(this["SHDocComment"]));
            }
            set {
                this["SHDocComment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IdFieldsVisible {
            get {
                return ((bool)(this["IdFieldsVisible"]));
            }
            set {
                this["IdFieldsVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastDirectory {
            get {
                return ((string)(this["LastDirectory"]));
            }
            set {
                this["LastDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AlohaFlyKitchen")]
        public string HotColdPrinterName {
            get {
                return ((string)(this["HotColdPrinterName"]));
            }
            set {
                this["HotColdPrinterName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AlohaFlyPack")]
        public string UpackPrinterName {
            get {
                return ((string)(this["UpackPrinterName"]));
            }
            set {
                this["UpackPrinterName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AlohaFlyConditer")]
        public string ConditerPrinterName {
            get {
                return ((string)(this["ConditerPrinterName"]));
            }
            set {
                this["ConditerPrinterName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int SHRidPlaceSVO {
            get {
                return ((int)(this["SHRidPlaceSVO"]));
            }
            set {
                this["SHRidPlaceSVO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int SHRidPlaceToGo {
            get {
                return ((int)(this["SHRidPlaceToGo"]));
            }
            set {
                this["SHRidPlaceToGo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("112")]
        public int SHToGoNotPaymentCatId {
            get {
                return ((int)(this["SHToGoNotPaymentCatId"]));
            }
            set {
                this["SHToGoNotPaymentCatId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public int SHUnitId {
            get {
                return ((int)(this["SHUnitId"]));
            }
            set {
                this["SHUnitId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int SHToFlyFolderId {
            get {
                return ((int)(this["SHToFlyFolderId"]));
            }
            set {
                this["SHToFlyFolderId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public int SHSharFolderId {
            get {
                return ((int)(this["SHSharFolderId"]));
            }
            set {
                this["SHSharFolderId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public int SHToGoFolderId {
            get {
                return ((int)(this["SHToGoFolderId"]));
            }
            set {
                this["SHToGoFolderId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("76")]
        public int SHNoCatFolderToFlyId {
            get {
                return ((int)(this["SHNoCatFolderToFlyId"]));
            }
            set {
                this["SHNoCatFolderToFlyId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("75")]
        public int SHNoCatFolderToGoId {
            get {
                return ((int)(this["SHNoCatFolderToGoId"]));
            }
            set {
                this["SHNoCatFolderToGoId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1812")]
        public int SHDeleveryToGo {
            get {
                return ((int)(this["SHDeleveryToGo"]));
            }
            set {
                this["SHDeleveryToGo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80")]
        public int SHOpenDishFolderToFly {
            get {
                return ((int)(this["SHOpenDishFolderToFly"]));
            }
            set {
                this["SHOpenDishFolderToFly"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("79")]
        public int SHOpenDishFolderToGo {
            get {
                return ((int)(this["SHOpenDishFolderToGo"]));
            }
            set {
                this["SHOpenDishFolderToGo"] = value;
            }
        }
    }
}
